# Generated by Django 4.2.1 on 2026-06-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('lifestyle', 'Lifestyle'), ('cooking', 'Cooking'), ('entertainment', 'Entertainment'), ('reviews', 'Reviews'), ('technology', 'Technology'), ('travel', 'Travel')], default='lifestyle', max_length=50),
        ),
    ]
