# Generated by Django 4.2.1 on 2026-06-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.CharField(blank=True, default='blog/images/default.svg', max_length=255),
        ),
    ]
