# Generated by Django 4.2.1 on 2026-06-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_image_alter_post_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='lifestyle', max_length=50),
        ),
    ]
