# Generated by Django 4.2.1 on 2026-06-24 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_alter_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create_post', 'Create Post'), ('edit_post', 'Edit Post'), ('delete_post', 'Delete Post'), ('view_post', 'View Post'), ('view_dashboard', 'View Dashboard'), ('refresh_token', 'Refresh Token'), ('verify_token', 'Verify Token')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='blog_userac_user_id_78050d_idx'), models.Index(fields=['action', '-timestamp'], name='blog_userac_action_e012b6_idx'), models.Index(fields=['timestamp'], name='blog_userac_timesta_471802_idx')],
            },
        ),
    ]
