# Generated by Django 4.2.1 on 2026-06-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_useractivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
