# Generated by Django 4.2.1 on 2026-06-24 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_useractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
    ]
