# Generated by Django 4.2.1 on 2026-06-25 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_remove_post_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Tell us about yourself')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('website', models.URLField(blank=True, help_text='Your personal website')),
                ('twitter', models.URLField(blank=True, help_text='Twitter profile URL')),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('github', models.URLField(blank=True, help_text='GitHub profile URL')),
                ('instagram', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('location', models.CharField(blank=True, help_text='Your location', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
